//
// BeersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class BeersAPI {
    /**
     Gets a beer with certain id
     
     - parameter beerId: (path) Beer id 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getBeerById(beerId: Int, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [Beer]?,_ error: Error?) -> Void)) {
        getBeerByIdWithRequestBuilder(beerId: beerId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Gets a beer with certain id
     - GET /beers/{beerId}
     - parameter beerId: (path) Beer id 
     - returns: RequestBuilder<[Beer]> 
     */
    open class func getBeerByIdWithRequestBuilder(beerId: Int) -> RequestBuilder<[Beer]> {
        var path = "/beers/{beerId}"
        let beerIdPreEscape = "\(APIHelper.mapValueToPathItem(beerId))"
        let beerIdPostEscape = beerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{beerId}", with: beerIdPostEscape, options: .literal, range: nil)
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Beer]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Gets a list of beers with pagination
     
     - parameter page: (query) Page number (optional)
     - parameter perPage: (query) Number of objects per page (optional)
     - parameter abvGt: (query) Returns all beers with ABV greater than the supplied number (optional)
     - parameter ibuGt: (query) Returns all beers with IBU greater than the supplied number (optional)
     - parameter ebcGt: (query) Returns all beers with EBC greater than the supplied number (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getBeers(page: Int? = nil, perPage: Int? = nil, abvGt: Int? = nil, ibuGt: Int? = nil, ebcGt: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [Beer]?,_ error: Error?) -> Void)) {
        getBeersWithRequestBuilder(page: page, perPage: perPage, abvGt: abvGt, ibuGt: ibuGt, ebcGt: ebcGt).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Gets a list of beers with pagination
     - GET /beers
     - parameter page: (query) Page number (optional)
     - parameter perPage: (query) Number of objects per page (optional)
     - parameter abvGt: (query) Returns all beers with ABV greater than the supplied number (optional)
     - parameter ibuGt: (query) Returns all beers with IBU greater than the supplied number (optional)
     - parameter ebcGt: (query) Returns all beers with EBC greater than the supplied number (optional)
     - returns: RequestBuilder<[Beer]> 
     */
    open class func getBeersWithRequestBuilder(page: Int? = nil, perPage: Int? = nil, abvGt: Int? = nil, ibuGt: Int? = nil, ebcGt: Int? = nil) -> RequestBuilder<[Beer]> {
        let path = "/beers"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": page?.encodeToJSON(), 
            "per_page": perPage?.encodeToJSON(), 
            "abv_gt": abvGt?.encodeToJSON(), 
            "ibu_gt": ibuGt?.encodeToJSON(), 
            "ebc_gt": ebcGt?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<[Beer]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Gets a random beer from the API, this takes no paramaters.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getRandomBeer(apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [Beer]?,_ error: Error?) -> Void)) {
        getRandomBeerWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Gets a random beer from the API, this takes no paramaters.
     - GET /beers/random
     - returns: RequestBuilder<[Beer]> 
     */
    open class func getRandomBeerWithRequestBuilder() -> RequestBuilder<[Beer]> {
        let path = "/beers/random"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Beer]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
